version: "3"
services:
  nodejs-appserver:
    build: .
    hostname: nodejs
    restart: always
    #command: node_modules/.bin/nodemon --exec npm start
    environment:
      NODE_ENV: development
    volumes:
      - .:/home/app
      - /home/app/node_modules
    expose:
      - 3000
    networks:
      net:
        ipv4_address: 172.2.1.2
networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.2.1.0/24